version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/proposalmate
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRE=30d
      - JWT_COOKIE_EXPIRE=30
      - STRIPE_SECRET_KEY=your_stripe_secret_key
      - STRIPE_WEBHOOK_SECRET=your_stripe_webhook_secret
      - STRIPE_PRICE_ID=your_stripe_price_id
      - SMTP_HOST=your_smtp_host
      - SMTP_PORT=your_smtp_port
      - SMTP_EMAIL=your_smtp_email
      - SMTP_PASSWORD=your_smtp_password
      - FROM_EMAIL=your_from_email
      - FROM_NAME=ProposalMate
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
